name: C++ Linter comment

permissions:
  actions: read
  pull-requests: write

on:
  pull_request:

jobs:
  comment-lint:
    if: ${{ github.repository_owner == 'oven-sh' }}
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun

      - name: Run clang-tidy
        id: env
        shell: bash
        run: |
          # Copy to outputs
          {
            echo 'text_output<<EOF'
            bun run clang-tidy:check
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Find Comment
        id: comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          body-includes: <!-- generated-comment lint-cpp-workflow=${{ github.workflow }} -->
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            @${{ github.actor }}, `clang-tidy` had something to share with you about your code:

            ```cpp
            ${{ steps.env.outputs.text_output }}
            ```

            Commit: ${{ github.event.workflow_run.head_sha || github.sha }}

            <!-- generated-comment lint-cpp-workflow=${{ github.workflow }} -->
          edit-mode: replace
